version: 1.1.0.{build}

platform: Any CPU
configuration: Release

skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore "./src/Egor92.Deferrals.sln"

build:
  project: src\Egor92.Deferrals.sln
  
test:
  assemblies:
    - '**\*.Tests.dll'
    
after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: /NuGet\\Egor92\.Deferrals\..*\.nupkg/
  
deploy:
  provider: NuGet
  api_key:
    secure: Enbbe1MRpwxTk+l70bA1DfoJq62BO4S01RRKFDL4Fx83I/f3W4D4MQJTRXrNwkFj
  skip_symbols: false
  artifact: /NuGet\.*\.nupkg/