version: 1.1.0.{build}

platform: Any CPU
configuration: Release

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore "./src/Egor92.Deferrals.sln"

build:
  project: src\Egor92.Deferrals.sln
  publish_nuget: true
  
test:
  assemblies:
    - '**\*.Tests.dll'
    
#after_test:
#  - ps: .\nuget\pack.ps1

artifacts:  
  - path: '**\*.nupkg'
    name: NuGet
  
deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: Enbbe1MRpwxTk+l70bA1DfoJq62BO4S01RRKFDL4Fx83I/f3W4D4MQJTRXrNwkFj
    skip_symbols: false
    artifact: /artifacts\*.nupkg/
  
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /artifacts\*.nupkg/
    draft: false
    prerelease: false
    #on:
      #branch: master
    appveyor_repo_tag: true